### ISSUE TITLE
Tool should display the usage if required args are missing

### ISSUE THREAD

**Issue by katzer** [appPlant/alpinepass#1]
If the tool has been executed with missing arguments, it should display the usage and exit. However it goes panic.

```
MacBerry:bin sebastian$ ./alpinepass 
panic: stat input.yml: no such file or directory

goroutine 1 [running]:
panic(0x16d980, 0x10530b00)
	/usr/local/go/src/runtime/panic.go:500 +0x325
github.com/appPlant/alpinepass/src/util.CheckError(0x22a8a0, 0x10530b00)
	/go/src/github.com/appPlant/alpinepass/src/util/util.go:13 +0x3e
github.com/appPlant/alpinepass/src/io.readFile(0x18de95, 0x9, 0x0, 0x0)
	/go/src/github.com/appPlant/alpinepass/src/io/input.go:16 +0x64
github.com/appPlant/alpinepass/src/io.ReadConfigs(0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/appPlant/alpinepass/src/io/parse.go:62 +0x4e
github.com/appPlant/alpinepass/src/app.execute(0x105b2000, 0x0, 0x0)
	/go/src/github.com/appPlant/alpinepass/src/app/execution.go:17 +0x62
github.com/appPlant/alpinepass/src/app.RunApp.func1(0x105b2000, 0x0, 0x0)
	/go/src/github.com/appPlant/alpinepass/src/app/application.go:51 +0x25
github.com/urfave/cli.HandleAction(0x166980, 0x1a81bc, 0x105b2000, 0x0, 0x0)
	/go/src/github.com/urfave/cli/app.go:485 +0x7f
github.com/urfave/cli.(*App).Run(0x105a25b0, 0x1052a0e0, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/urfave/cli/app.go:259 +0xa58
github.com/appPlant/alpinepass/src/app.RunApp()
	/go/src/github.com/appPlant/alpinepass/src/app/application.go:54 +0x565
main.main()
	/root/code/src/alpinepass.go:6 +0x11
```

**Comment by EightBitBoy** [comment]
When an error occurs a descriptive message is shown and the app's usage is printed!

**Comment by EightBitBoy** [comment]
@katzer You can review the changes and close the issue!
